"""Build the native extension of the Python bindings.

Run from anywhere in the pixi environment::

    pixi run python python/sqpopt/_build.py

Steps:

1. build the Fortran library (release profile, position-independent code)
   with fpm, and install it (``libsqpopt.a`` and the ``.mod`` files) under
   ``python/build/fortran``;
2. generate the Fortran option setter (``sqpopt_python_options.f90``) from
   the options schema (``sqpopt_options.schema``), so every option the
   options dialog knows can be set from Python;
3. compile it and the implementation of the wrapped module
   (``fortran/sqpopt_python_core.f90``) into ``libsqpopt_python.a``;
4. build the extension from the wrapped module ``fortran/sqpopt_python.f90``
   with PRIK, linked with both libraries, and copy it into the package as
   ``sqpopt/_sqpopt<suffix>``.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import sysconfig
import zlib
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent             # python/sqpopt
PYTHON_DIR = PACKAGE.parent                           # python
ROOT = PYTHON_DIR.parent                              # the repository
BUILD = PYTHON_DIR / 'build'
EXTENSION = '_sqpopt'

sys.path.insert(0, str(PYTHON_DIR))
from sqpopt_options import schema  # noqa: E402

#: the Fortran object each option path starts with, as named in the generated setter's arguments
OBJECTS = ('options', 'hessian', 'qp_solver', 'linesearch', 'trust_region')


def options_signature() -> int:
    """checksum of the options' order, names, and kinds (the generated numbering)"""
    text = '\n'.join(f'{o.fortran}:{o.kind}' for o in schema.OPTIONS.values())
    return zlib.crc32(text.encode()) & 0x7FFFFFFF


def generate_option_setter(path: Path) -> None:
    """write the Fortran module that sets an option by its number (its 1-based position in the schema)"""
    cases = []
    for i, o in enumerate(schema.OPTIONS.values(), start=1):
        if o.path[0] not in OBJECTS:
            raise ValueError(f'{o.fortran}: unknown object')
        if o.kind == 'float':
            value = 'value'
        elif o.kind == 'bool':
            value = 'value /= 0.0_real64'
        else:
            value = 'nint(value)'
        cases.append(f'        case ({i}); {o.fortran} = {value}')
    text = f"""!  Generated by python/sqpopt/_build.py from the options schema: do not edit.

    module sqpopt_python_options

    use, intrinsic :: iso_fortran_env, only: real64, int32
    use sqpopt_options_module,      only: sqpopt_options_type
    use sqpopt_hessian_module,      only: sqpopt_hessian_type
    use sqpopt_qp_solver_module,    only: sqpopt_qp_solver_type
    use sqpopt_linesearch_module,   only: sqpopt_linesearch_type
    use sqpopt_trust_region_module, only: sqpopt_trust_region_type

    implicit none

    private

    integer(int32), parameter, public :: sqpopt_python_n_options = {len(schema.OPTIONS)} !! number of options
    integer(int32), parameter, public :: sqpopt_python_options_signature = {options_signature()} !! checksum

    public :: sqpopt_python_set_option

    contains

    subroutine sqpopt_python_set_option(id, value, options, hessian, qp_solver, linesearch, trust_region, ok)
    !! set option number `id` (integers and logicals are given as reals)
    integer(int32),                 intent(in)    :: id           !! the option's number
    real(real64),                   intent(in)    :: value        !! its value
    type(sqpopt_options_type),      intent(inout) :: options      !! solver options
    type(sqpopt_hessian_type),      intent(inout) :: hessian      !! Hessian settings
    type(sqpopt_qp_solver_type),    intent(inout) :: qp_solver    !! QP solver settings
    type(sqpopt_linesearch_type),   intent(inout) :: linesearch   !! line search settings
    type(sqpopt_trust_region_type), intent(inout) :: trust_region !! trust region settings
    logical,                        intent(out)   :: ok           !! whether `id` is a valid option number
    ok = .true.
    select case (id)
{chr(10).join(cases)}
        case default; ok = .false.
    end select
    end subroutine sqpopt_python_set_option

    end module sqpopt_python_options
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def build_library(prefix: Path) -> None:
    """build and install the Fortran library with fpm"""
    subprocess.run(['fpm', 'install', '--profile', 'release', '--flag', '-fPIC', '--prefix', str(prefix)],
                   cwd=ROOT, check=True)


def compile_core(prefix: Path, sources: list[Path]) -> tuple[Path, Path]:
    """compile the modules the PRIK-wrapped module uses (in order) into a static library; returns it and the
    directory of their ``.mod`` files. (PRIK compiles its native sources concurrently with the wrapped
    module, which needs their ``.mod`` files first.)"""
    obj = BUILD / 'core'
    if obj.exists():
        shutil.rmtree(obj)
    obj.mkdir(parents=True)
    objects = []
    for source in sources:
        o = obj / (source.stem + '.o')
        # (-Wconversion -Werror: an implicit narrowing conversion in the generated option setter would mean
        # an option's kind in the schema disagrees with its Fortran type)
        subprocess.run(['gfortran', '-O2', '-fPIC', '-Wconversion', '-Werror', f'-I{prefix / "include"}',
                        f'-J{obj}', '-c', str(source), '-o', str(o)], check=True)
        objects.append(o)
    library = obj / 'libsqpopt_python.a'
    subprocess.run(['ar', 'rcs', str(library), *map(str, objects)], check=True)
    return library, obj


def _use_dynamic_lookup() -> list[str]:
    """work around a PRIK issue: with a statically linked Python (as conda's), PRIK still links the
    extension with ``libpython``, so it runs on a second copy of the interpreter and crashes on import.
    Link it against the running interpreter's symbols instead (as Python's own ``LDSHARED`` does).
    Returns the extra link flags."""
    if sysconfig.get_config_var('Py_ENABLE_SHARED'):
        return []
    import prik.compiler.compiler_profiles as profiles
    for toolchain in profiles.available_compilers.values():
        for language in toolchain.values():
            for key in ('dependencies', 'libdir', 'libs'):
                language['python'].pop(key, None)
    return ['-undefined', 'dynamic_lookup'] if sys.platform == 'darwin' else []


def build(verbose: bool = False) -> Path:
    """build the extension, and return its path in the package"""
    prefix = BUILD / 'fortran'
    build_library(prefix)
    options_source = BUILD / 'generated' / 'sqpopt_python_options.f90'
    generate_option_setter(options_source)

    core_library, core_modules = compile_core(prefix, [options_source, PACKAGE / 'fortran' / 'sqpopt_python_core.f90'])

    link_flags = _use_dynamic_lookup()
    from prik import build_fortran_extension
    result = build_fortran_extension(
        PACKAGE / 'fortran' / 'sqpopt_python.f90',
        output_dir=BUILD / 'prik',
        output_name=EXTENSION,
        export_symbols=['sqpopt_python::solve', 'sqpopt_python::n_info'],
        native_include_dirs=[core_modules, prefix / 'include'],
        native_fortran_flags=['-O2', f'-I{core_modules}', f'-I{prefix / "include"}'],
        native_objects=[core_library, prefix / 'lib' / 'libsqpopt.a'],
        wrapper_fortran_flags=[f'-I{core_modules}', f'-I{prefix / "include"}'],
        wrapper_c_flags=link_flags,
        verbose=verbose,
    )
    target = PACKAGE / (EXTENSION + sysconfig.get_config_var('EXT_SUFFIX'))
    shutil.copy2(result.shared_library, target)
    stray = Path.cwd() / f'{EXTENSION}.so'   # (PRIK's stable alias, which points into the build directory)
    if stray.is_symlink() or stray.exists():
        stray.unlink()
    print(f'built {target}')
    return target


if __name__ == '__main__':
    build(verbose='-v' in sys.argv[1:])
