"""Build the native extension of the Python bindings.

Run from anywhere in the pixi environment::

    pixi run python python/sqpopt/_build.py

Steps:

1. build the Fortran library (release profile, position-independent code)
   with fpm, and install it (``libsqpopt.a`` and the ``.mod`` files) under
   ``python/build/fortran``;
2. generate the Fortran option setter (``sqpopt_python_options.f90``) from
   the options schema (``sqpopt_options.schema``), so every option the
   options dialog knows can be set from Python;
3. compile it and the bindings' module (``fortran/sqpopt_python.f90``) into
   ``libsqpopt_python.a``;
4. build the extension with f2py (meson backend) from the signature file
   ``fortran/_sqpopt.pyf`` and the routines it describes
   (``fortran/sqpopt_python_f2py.f90``), linked with both libraries, and copy
   it into the package as ``sqpopt/_sqpopt<suffix>``.

Run with ``-v`` to see f2py's output, and with ``--mumps`` to build the
library with MUMPS (the ``HAS_MUMPS`` preprocessor directive, for the
``inertia_control`` option): the sequential MUMPS library (conda-forge's
``mumps-seq``) must be in the environment (``CONDA_PREFIX``).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import sysconfig
import zlib
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent             # python/sqpopt
PYTHON_DIR = PACKAGE.parent                           # python
ROOT = PYTHON_DIR.parent                              # the repository
BUILD = PYTHON_DIR / 'build'
EXTENSION = '_sqpopt'

sys.path.insert(0, str(PYTHON_DIR))
from sqpopt_options import schema  # noqa: E402

#: the Fortran object each option path starts with, as named in the generated setter's arguments
OBJECTS = ('options', 'hessian', 'qp_solver', 'linesearch', 'trust_region')


def options_signature() -> int:
    """checksum of the options' order, names, and kinds (the generated numbering)"""
    text = '\n'.join(f'{o.fortran}:{o.kind}' for o in schema.OPTIONS.values())
    return zlib.crc32(text.encode()) & 0x7FFFFFFF


def generate_option_setter(path: Path) -> None:
    """write the Fortran module that sets an option by its number (its 1-based position in the schema)"""
    cases = []
    for i, o in enumerate(schema.OPTIONS.values(), start=1):
        if o.path[0] not in OBJECTS:
            raise ValueError(f'{o.fortran}: unknown object')
        if o.kind == 'float':
            value = 'value'
        elif o.kind == 'bool':
            value = 'value /= 0.0_real64'
        else:
            value = 'nint(value)'
        cases.append(f'        case ({i}); {o.fortran} = {value}')
    text = f"""!  Generated by python/sqpopt/_build.py from the options schema: do not edit.

    module sqpopt_python_options

    use, intrinsic :: iso_fortran_env, only: real64, int32
    use sqpopt_options_module,      only: sqpopt_options_type
    use sqpopt_hessian_module,      only: sqpopt_hessian_type
    use sqpopt_qp_solver_module,    only: sqpopt_qp_solver_type
    use sqpopt_linesearch_module,   only: sqpopt_linesearch_type
    use sqpopt_trust_region_module, only: sqpopt_trust_region_type

    implicit none

    private

    integer(int32), parameter, public :: sqpopt_python_n_options = {len(schema.OPTIONS)} !! number of options
    integer(int32), parameter, public :: sqpopt_python_options_signature = {options_signature()} !! checksum

    public :: sqpopt_python_set_option

    contains

    subroutine sqpopt_python_set_option(id, value, options, hessian, qp_solver, linesearch, trust_region, ok)
    !! set option number `id` (integers and logicals are given as reals)
    integer(int32),                 intent(in)    :: id           !! the option's number
    real(real64),                   intent(in)    :: value        !! its value
    type(sqpopt_options_type),      intent(inout) :: options      !! solver options
    type(sqpopt_hessian_type),      intent(inout) :: hessian      !! Hessian settings
    type(sqpopt_qp_solver_type),    intent(inout) :: qp_solver    !! QP solver settings
    type(sqpopt_linesearch_type),   intent(inout) :: linesearch   !! line search settings
    type(sqpopt_trust_region_type), intent(inout) :: trust_region !! trust region settings
    logical,                        intent(out)   :: ok           !! whether `id` is a valid option number
    ok = .true.
    select case (id)
{chr(10).join(cases)}
        case default; ok = .false.
    end select
    end subroutine sqpopt_python_set_option

    end module sqpopt_python_options
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


#: the sequential, double precision MUMPS library (linked with ``--mumps``)
MUMPS_LIBRARY = 'dmumps_seq'


def build_library(prefix: Path, mumps: bool = False) -> None:
    """build and install the Fortran library with fpm (with MUMPS, if `mumps`)"""
    command = ['fpm', 'install', '--profile', 'release', '--prefix', str(prefix)]
    if mumps:
        # (the link flag is for the example programs, which fpm builds too)
        command += ['--flag', f'-fPIC -DHAS_MUMPS -I{Path(os.environ["CONDA_PREFIX"]) / "include"}',
                    '--link-flag', f'-l{MUMPS_LIBRARY}']
    else:
        command += ['--flag', '-fPIC']
    subprocess.run(command, cwd=ROOT, check=True)


def compile_core(prefix: Path, sources: list[Path]) -> tuple[Path, Path]:
    """compile the modules the f2py-wrapped routines use (in order) into a static library; returns it and the
    directory of their ``.mod`` files"""
    obj = BUILD / 'core'
    if obj.exists():
        shutil.rmtree(obj)
    obj.mkdir(parents=True)
    objects = []
    for source in sources:
        o = obj / (source.stem + '.o')
        # (-Wconversion -Werror: an implicit narrowing conversion in the generated option setter would mean
        # an option's kind in the schema disagrees with its Fortran type)
        subprocess.run(['gfortran', '-O2', '-fPIC', '-Wconversion', '-Werror', f'-I{prefix / "include"}',
                        f'-J{obj}', '-c', str(source), '-o', str(o)], check=True)
        objects.append(o)
    library = obj / 'libsqpopt_python.a'
    subprocess.run(['ar', 'rcs', str(library), *map(str, objects)], check=True)
    return library, obj


def build(verbose: bool = False, mumps: bool = False) -> Path:
    """build the extension (with MUMPS, if `mumps`), and return its path in the package"""
    prefix = BUILD / 'fortran'
    build_library(prefix, mumps)
    options_source = BUILD / 'generated' / 'sqpopt_python_options.f90'
    generate_option_setter(options_source)

    fortran = PACKAGE / 'fortran'
    core_library, core_modules = compile_core(prefix, [options_source, fortran / 'sqpopt_python.f90'])

    work = BUILD / 'f2py'
    if work.exists():
        shutil.rmtree(work)
    work.mkdir(parents=True)
    command = [sys.executable, '-m', 'numpy.f2py', '-c', str(fortran / '_sqpopt.pyf'),
               str(fortran / 'sqpopt_python_f2py.f90'),
               f'-I{core_modules}', f'-I{prefix / "include"}',
               f'-L{core_modules}', '-lsqpopt_python', f'-L{prefix / "lib"}', '-lsqpopt',
               '--build-dir', str(work / 'meson')]
    if mumps:
        command += [f'-L{Path(os.environ["CONDA_PREFIX"]) / "lib"}', f'-l{MUMPS_LIBRARY}']
    completed = subprocess.run(command, cwd=work, capture_output=not verbose, text=True)
    if completed.returncode != 0:
        if not verbose:
            print(completed.stdout[-5000:], completed.stderr[-5000:], sep='\n')
        raise RuntimeError('f2py failed')
    built = list(work.glob(EXTENSION + '*' + sysconfig.get_config_var('EXT_SUFFIX')))
    if len(built) != 1:
        raise RuntimeError(f'f2py built {built}')
    target = PACKAGE / built[0].name
    shutil.copy2(built[0], target)
    print(f'built {target}')
    return target


if __name__ == '__main__':
    build(verbose='-v' in sys.argv[1:], mumps='--mumps' in sys.argv[1:])
