!*******************************************************************************
!>
!  A modern interface to the Schittkowski/Hock-Schittkowski test problem
!  collection (see [[schittkowski_problems_module]], generated from the
!  original `PROB.FOR`), for benchmarking `sqpopt`:
!
!      minimize f(x)  s.t.  c_lb <= c(x) <= c_ub,  x_lb <= x <= x_ub
!
!  [[hs_setup]] returns a problem's size, starting point, bounds, and
!  validated optimal solution; [[hs_f]], [[hs_g]], [[hs_c]], and [[hs_jac]] evaluate
!  it. The original problems' constraints are `g(x) >= 0` (inequalities,
!  first) and `g(x) = 0` (equalities, last); here they are returned in that
!  order, with bounds `[0,+inf]` and `[0,0]`. Absent variable bounds are
!  `-/+ hs_infinity`.
!
!  Also included, for comparison, are the numbers of function and gradient
!  evaluations used by Schittkowski's NLPQLP on each problem (from the
!  original `TEST.DAT`; its gradients were approximated by forward
!  differences).
!
!  This file was generated by `tools/convert_schittkowski.py` (do not edit
!  it by hand).

    module hs_problems_module

    use sqpopt_kinds, only: dp => sqpopt_module_wp
    use schittkowski_problems_module

    implicit none

    private

    integer, parameter :: nmax = 101, mmax = 50  !! sizes of the original COMMON blocks

    real(dp), parameter, public :: hs_infinity = 1.0e20_dp  !! value used for absent bounds

    integer, parameter, public :: hs_n_problems = 305  !! number of problems in the collection
    integer, dimension(hs_n_problems), parameter, public :: hs_problem_ids = [ &
               1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,   15, &
              16,   17,   18,   19,   20,   21,   22,   23,   24,   25,   26,   27,   28,   29,   30, &
              31,   32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45, &
              46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,   57,   59,   60,   61, &
              62,   63,   64,   65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76, &
              77,   78,   79,   80,   81,   83,   84,   85,   86,   87,   88,   89,   90,   91,   92, &
              93,   95,   96,   97,   98,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108, &
             109,  110,  111,  112,  113,  114,  116,  117,  118,  119,  201,  202,  203,  204,  205, &
             206,  207,  208,  209,  210,  211,  212,  213,  214,  215,  216,  217,  218,  219,  220, &
             221,  222,  223,  224,  225,  226,  227,  228,  229,  230,  231,  232,  233,  234,  235, &
             236,  237,  238,  239,  240,  241,  242,  243,  244,  245,  246,  247,  248,  249,  250, &
             251,  252,  253,  254,  255,  256,  257,  258,  259,  260,  261,  262,  263,  264,  265, &
             266,  267,  268,  269,  270,  271,  272,  273,  274,  275,  276,  277,  278,  279,  280, &
             281,  282,  283,  284,  285,  286,  287,  288,  289,  290,  291,  292,  293,  294,  295, &
             296,  297,  298,  299,  300,  301,  302,  303,  304,  305,  307,  308,  309,  310,  311, &
             312,  314,  315,  316,  317,  318,  319,  320,  321,  322,  323,  324,  325,  326,  327, &
             328,  329,  330,  331,  332,  333,  334,  335,  336,  337,  338,  339,  340,  341,  342, &
             343,  344,  345,  346,  347,  348,  350,  351,  352,  353,  354,  355,  356,  357,  358, &
             359,  360,  361,  362,  364,  365,  366,  367,  368,  369,  370,  371,  372,  373,  374, &
             375,  376,  377,  378,  379,  380,  381,  382,  383,  384,  385,  386,  387,  388,  389, &
             391,  392,  393,  394,  395 ] !! the problem numbers

    ! NLPQLP's evaluation counts on each problem (from the original TEST.DAT):
    integer, dimension(hs_n_problems), parameter, public :: hs_nlpqlp_nf = [ &
              26,   20,   10,    2,    8,   10,   13,    5,    6,   14,   10,   11,   50,    6,    3, &
               5,   21,    8,    7,    5,    3,    7,    7,    5,    1,   17,   37,    5,   13,   14, &
              12,    3,    5,    8,    7,    2,    8,  100,   14,    6,    8,   10,   14,    6,    8, &
              14,   17,    9,    9,   18,    5,    8,    8,   12,    2,   11,    6,   17,   10,    9, &
              14,    8,  149,    8,    7,   20,   33,   63,   37,    5,   22,    5,   10,    9,    6, &
              16,    8,   10,    7,    8,   35,   72,   91,    6,   20,   26,   34,   26,   33,   41, &
              15,    2,    2,    7,    7,   70,   20,   66,   55,   37,   19,    2,  283,    8,   13, &
              23,   10,   51,   37,   16,   36,   84,   16,   19,   12,    5,   16,   12,    7,   14, &
              10,   14,   47,  182,    7,   26,   19,   21,   55,    7,   15,    9,   14,   18,   27, &
              25,    7,    9,    4,    7,    7,    6,    7,   30,    5,   47,    5,   18,   13,   21, &
               6,   10,   14,    6,    5,   34,   11,   11,   18,   20,   26,    5,   16,   14,    2, &
               8,   39,    6,    9,   20,   36,   42,  120,   27,  121,   35,    7,   14,   12,    2, &
               8,   35,   22,    8,    9,   25,   40,   55,    6,    5,    9,    5,    8,    8,   11, &
             204,  177,    7,   65,   45,  165,   27,   65,    8,   19,   69,  195,  245,   72,  114, &
              31,   33,   33,   33,   41,  101,  201,   20,    8,    8,   30,   14,   14,   15,   18, &
             155,    9,   11,    7,    9,   10,   12,   17,   15,   21,    9,    8,    8,    8,    6, &
              24,    7,   10,    9,  707,   27,   33,   20,   23,   11,   43,   12,    8,   13,   13, &
               5,   10,   29,    5,    2,   36,   14,   34,   14,    2,   20,  389,   10,   11,   27, &
               3,   67,    4,    1,   30,   15,   17,   16,    9,   34,   38,   42,   27,   16,   57, &
              46,   17,    2,   51,   69,  316,    7,   12,  123,   57,   52,   62,   64,   47,   41, &
             175,   15,   90,  181,  473 ] !! objective evaluations
    integer, dimension(hs_n_problems), parameter, public :: hs_nlpqlp_ndf = [ &
              19,   15,   10,    2,    6,    9,   12,    5,    6,   12,    9,   10,   50,    6,    3, &
               5,   17,    8,    7,    5,    2,    6,    7,    5,    1,   15,   22,    4,   12,   14, &
               7,    3,    5,    8,    7,    2,    8,   78,   12,    6,    8,    8,   11,    6,    8, &
              12,   13,    8,    6,   14,    3,    6,    7,   11,    2,    9,    4,   15,    9,    8, &
               9,    8,   80,    8,    7,   20,   26,   40,   34,    5,   22,    5,   10,    9,    6, &
              15,    8,    9,    7,    8,    5,   44,   56,    5,   16,   20,   22,   20,   23,   30, &
              12,    2,    2,    7,    7,   19,   14,   39,   35,   26,   17,    2,  109,    8,   13, &
              18,    7,   51,   21,   13,   32,   61,   16,   19,    9,    3,   12,   10,    6,   12, &
               7,   13,   34,  129,    5,   20,   12,   15,   27,    7,   11,    9,   14,   17,   27, &
              25,    6,    9,    4,    7,    7,    5,    7,   24,    4,   35,    5,   14,   13,   18, &
               6,   10,   13,    6,    3,   25,   11,    7,   17,   19,   19,    2,   13,   14,    2, &
               8,   25,    6,    9,   12,   27,   29,   90,   15,   91,   32,    7,   14,    9,    2, &
               7,   32,   11,    7,    8,    7,   36,   30,    5,    4,    8,    5,    8,    8,   11, &
              80,  125,    2,   31,   20,   97,   27,   39,    7,   17,   41,   73,   95,   67,  107, &
              31,   33,   33,   33,   21,   51,  101,   14,    2,    2,   21,   11,   10,    9,   10, &
             117,    7,   10,    6,    7,    8,    9,   11,   10,   14,    7,    8,    7,    7,    4, &
              17,    7,   10,    7,   93,   20,   24,   19,   16,    8,   24,   11,    8,   12,   12, &
               5,    9,   20,    5,    2,   22,   13,   26,    7,    2,   14,  185,   10,   11,   18, &
               3,   41,    4,    1,   26,   15,   16,   12,    9,   33,   31,   32,   20,   15,   38, &
              25,   17,    2,   51,   52,  202,    7,   11,   54,   25,   25,   32,   33,   29,   24, &
              54,   15,   89,  114,  227 ] !! gradient evaluations

    type, public :: hs_problem
        !! a test problem's definition and known solution
        integer  :: id = 0   !! problem number
        integer  :: n  = 0   !! number of variables
        integer  :: m  = 0   !! number of constraints
        integer  :: me = 0   !! number of equality constraints (the last `me` of the `m`)
        real(dp), dimension(:), allocatable :: x0    !! starting point `dimension(n)`
        real(dp), dimension(:), allocatable :: x_lb  !! variable lower bounds `dimension(n)`
        real(dp), dimension(:), allocatable :: x_ub  !! variable upper bounds `dimension(n)`
        real(dp), dimension(:), allocatable :: c_lb  !! constraint lower bounds `dimension(m)`
        real(dp), dimension(:), allocatable :: c_ub  !! constraint upper bounds `dimension(m)`
        real(dp) :: f_star = 0.0_dp                  !! the (validated) optimal objective value
        real(dp), dimension(:), allocatable :: x_star !! an optimal point `dimension(n)`
        logical  :: exact = .false.                  !! whether that solution is known analytically (else it
                                                     !! was computed numerically, and validated)
    end type hs_problem

    public :: hs_setup, hs_f, hs_g, hs_c, hs_jac, hs_index

    ! the original COMMON blocks (see `PROB.FOR`):
    integer  :: n_, nili, ninl, neli, nenl
    real(dp) :: x_(nmax), g_(mmax), gf_(nmax), gg_(mmax,nmax), fx_
    logical  :: index1(mmax), index2(mmax), lxl(nmax), lxu(nmax), lex
    real(dp) :: xl(nmax), xu(nmax), fex, xex(nmax)
    integer  :: nex
    common /l1/  n_, nili, ninl, neli, nenl
    common /l2/  x_
    common /l3/  g_
    common /l4/  gf_
    common /l5/  gg_
    common /l6/  fx_
    common /l9/  index1
    common /l10/ index2
    common /l11/ lxl
    common /l12/ lxu
    common /l13/ xl
    common /l14/ xu
    common /l20/ lex, nex, fex, xex

    contains
!*******************************************************************************

!*******************************************************************************
!>
!  position of problem `id` in [[hs_problem_ids]] (0 if there is no such problem).

    pure integer function hs_index(id)

    integer, intent(in) :: id

    integer :: k

    hs_index = 0
    do k = 1, hs_n_problems
        if (hs_problem_ids(k) == id) then
            hs_index = k
            return
        end if
    end do

    end function hs_index
!*******************************************************************************

!*******************************************************************************
!>
!  call the original problem routine for problem `id` (the equivalent of
!  the original `CONV.FOR`).

    subroutine call_problem(id, mode)

    integer, intent(in) :: id, mode

    select case (id)
        case (  1); call tp1(mode)
        case (  2); call tp2(mode)
        case (  3); call tp3(mode)
        case (  4); call tp4(mode)
        case (  5); call tp5(mode)
        case (  6); call tp6(mode)
        case (  7); call tp7(mode)
        case (  8); call tp8(mode)
        case (  9); call tp9(mode)
        case ( 10); call tp10(mode)
        case ( 11); call tp11(mode)
        case ( 12); call tp12(mode)
        case ( 13); call tp13(mode)
        case ( 14); call tp14(mode)
        case ( 15); call tp15(mode)
        case ( 16); call tp16(mode)
        case ( 17); call tp17(mode)
        case ( 18); call tp18(mode)
        case ( 19); call tp19(mode)
        case ( 20); call tp20(mode)
        case ( 21); call tp21(mode)
        case ( 22); call tp22(mode)
        case ( 23); call tp23(mode)
        case ( 24); call tp24(mode)
        case ( 25); call tp25(mode)
        case ( 26); call tp26(mode)
        case ( 27); call tp27(mode)
        case ( 28); call tp28(mode)
        case ( 29); call tp29(mode)
        case ( 30); call tp30(mode)
        case ( 31); call tp31(mode)
        case ( 32); call tp32(mode)
        case ( 33); call tp33(mode)
        case ( 34); call tp34(mode)
        case ( 35); call tp35(mode)
        case ( 36); call tp36(mode)
        case ( 37); call tp37(mode)
        case ( 38); call tp38(mode)
        case ( 39); call tp39(mode)
        case ( 40); call tp40(mode)
        case ( 41); call tp41(mode)
        case ( 42); call tp42(mode)
        case ( 43); call tp43(mode)
        case ( 44); call tp44(mode)
        case ( 45); call tp45(mode)
        case ( 46); call tp46(mode)
        case ( 47); call tp47(mode)
        case ( 48); call tp48(mode)
        case ( 49); call tp49(mode)
        case ( 50); call tp50(mode)
        case ( 51); call tp51(mode)
        case ( 52); call tp52(mode)
        case ( 53); call tp53(mode)
        case ( 54); call tp54(mode)
        case ( 55); call tp55(mode)
        case ( 56); call tp56(mode)
        case ( 57); call tp57(mode)
        case ( 59); call tp59(mode)
        case ( 60); call tp60(mode)
        case ( 61); call tp61(mode)
        case ( 62); call tp62(mode)
        case ( 63); call tp63(mode)
        case ( 64); call tp64(mode)
        case ( 65); call tp65(mode)
        case ( 66); call tp66(mode)
        case ( 67); call tp67(mode)
        case ( 68); call tp68(mode)
        case ( 69); call tp69(mode)
        case ( 70); call tp70(mode)
        case ( 71); call tp71(mode)
        case ( 72); call tp72(mode)
        case ( 73); call tp73(mode)
        case ( 74); call tp74(mode)
        case ( 75); call tp75(mode)
        case ( 76); call tp76(mode)
        case ( 77); call tp77(mode)
        case ( 78); call tp78(mode)
        case ( 79); call tp79(mode)
        case ( 80); call tp80(mode)
        case ( 81); call tp81(mode)
        case ( 83); call tp83(mode)
        case ( 84); call tp84(mode)
        case ( 85); call tp85(mode)
        case ( 86); call tp86(mode)
        case ( 87); call tp87(mode)
        case ( 88); call tp88(mode)
        case ( 89); call tp89(mode)
        case ( 90); call tp90(mode)
        case ( 91); call tp91(mode)
        case ( 92); call tp92(mode)
        case ( 93); call tp93(mode)
        case ( 95); call tp95(mode)
        case ( 96); call tp96(mode)
        case ( 97); call tp97(mode)
        case ( 98); call tp98(mode)
        case ( 99); call tp99(mode)
        case (100); call tp100(mode)
        case (101); call tp101(mode)
        case (102); call tp102(mode)
        case (103); call tp103(mode)
        case (104); call tp104(mode)
        case (105); call tp105(mode)
        case (106); call tp106(mode)
        case (107); call tp107(mode)
        case (108); call tp108(mode)
        case (109); call tp109(mode)
        case (110); call tp110(mode)
        case (111); call tp111(mode)
        case (112); call tp112(mode)
        case (113); call tp113(mode)
        case (114); call tp114(mode)
        case (116); call tp116(mode)
        case (117); call tp117(mode)
        case (118); call tp118(mode)
        case (119); call tp119(mode)
        case (201); call tp201(mode)
        case (202); call tp202(mode)
        case (203); call tp203(mode)
        case (204); call tp204(mode)
        case (205); call tp205(mode)
        case (206); call tp206(mode)
        case (207); call tp207(mode)
        case (208); call tp208(mode)
        case (209); call tp209(mode)
        case (210); call tp210(mode)
        case (211); call tp211(mode)
        case (212); call tp212(mode)
        case (213); call tp213(mode)
        case (214); call tp214(mode)
        case (215); call tp215(mode)
        case (216); call tp216(mode)
        case (217); call tp217(mode)
        case (218); call tp218(mode)
        case (219); call tp219(mode)
        case (220); call tp220(mode)
        case (221); call tp221(mode)
        case (222); call tp222(mode)
        case (223); call tp223(mode)
        case (224); call tp224(mode)
        case (225); call tp225(mode)
        case (226); call tp226(mode)
        case (227); call tp227(mode)
        case (228); call tp228(mode)
        case (229); call tp229(mode)
        case (230); call tp230(mode)
        case (231); call tp231(mode)
        case (232); call tp232(mode)
        case (233); call tp233(mode)
        case (234); call tp234(mode)
        case (235); call tp235(mode)
        case (236); call tp236(mode)
        case (237); call tp237(mode)
        case (238); call tp238(mode)
        case (239); call tp239(mode)
        case (240); call tp240(mode)
        case (241); call tp241(mode)
        case (242); call tp242(mode)
        case (243); call tp243(mode)
        case (244); call tp244(mode)
        case (245); call tp245(mode)
        case (246); call tp246(mode)
        case (247); call tp247(mode)
        case (248); call tp248(mode)
        case (249); call tp249(mode)
        case (250); call tp250(mode)
        case (251); call tp251(mode)
        case (252); call tp252(mode)
        case (253); call tp253(mode)
        case (254); call tp254(mode)
        case (255); call tp255(mode)
        case (256); call tp256(mode)
        case (257); call tp257(mode)
        case (258); call tp258(mode)
        case (259); call tp259(mode)
        case (260); call tp260(mode)
        case (261); call tp261(mode)
        case (262); call tp262(mode)
        case (263); call tp263(mode)
        case (264); call tp264(mode)
        case (265); call tp265(mode)
        case (266); call tp266(mode)
        case (267); call tp267(mode)
        case (268); call tp268(mode)
        case (269); call tp269(mode)
        case (270); call tp270(mode)
        case (271); call tp271(mode)
        case (272); call tp272(mode)
        case (273); call tp273(mode)
        case (274); call tp274(mode)
        case (275); call tp275(mode)
        case (276); call tp276(mode)
        case (277); call tp277(mode)
        case (278); call tp278(mode)
        case (279); call tp279(mode)
        case (280); call tp280(mode)
        case (281); call tp281(mode)
        case (282); call tp282(mode)
        case (283); call tp283(mode)
        case (284); call tp284(mode)
        case (285); call tp285(mode)
        case (286); call tp286(mode)
        case (287); call tp287(mode)
        case (288); call tp288(mode)
        case (289); call tp289(mode)
        case (290); call tp290(mode)
        case (291); call tp291(mode)
        case (292); call tp292(mode)
        case (293); call tp293(mode)
        case (294); call tp294(mode)
        case (295); call tp295(mode)
        case (296); call tp296(mode)
        case (297); call tp297(mode)
        case (298); call tp298(mode)
        case (299); call tp299(mode)
        case (300); call tp300(mode)
        case (301); call tp301(mode)
        case (302); call tp302(mode)
        case (303); call tp303(mode)
        case (304); call tp304(mode)
        case (305); call tp305(mode)
        case (307); call tp307(mode)
        case (308); call tp308(mode)
        case (309); call tp309(mode)
        case (310); call tp310(mode)
        case (311); call tp311(mode)
        case (312); call tp312(mode)
        case (314); call tp314(mode)
        case (315); call tp315(mode)
        case (316); call tp316(mode)
        case (317); call tp317(mode)
        case (318); call tp318(mode)
        case (319); call tp319(mode)
        case (320); call tp320(mode)
        case (321); call tp321(mode)
        case (322); call tp322(mode)
        case (323); call tp323(mode)
        case (324); call tp324(mode)
        case (325); call tp325(mode)
        case (326); call tp326(mode)
        case (327); call tp327(mode)
        case (328); call tp328(mode)
        case (329); call tp329(mode)
        case (330); call tp330(mode)
        case (331); call tp331(mode)
        case (332); call tp332(mode)
        case (333); call tp333(mode)
        case (334); call tp334(mode)
        case (335); call tp335(mode)
        case (336); call tp336(mode)
        case (337); call tp337(mode)
        case (338); call tp338(mode)
        case (339); call tp339(mode)
        case (340); call tp340(mode)
        case (341); call tp341(mode)
        case (342); call tp342(mode)
        case (343); call tp343(mode)
        case (344); call tp344(mode)
        case (345); call tp345(mode)
        case (346); call tp346(mode)
        case (347); call tp347(mode)
        case (348); call tp348(mode)
        case (350); call tp350(mode)
        case (351); call tp351(mode)
        case (352); call tp352(mode)
        case (353); call tp353(mode)
        case (354); call tp354(mode)
        case (355); call tp355(mode)
        case (356); call tp356(mode)
        case (357); call tp357(mode)
        case (358); call tp358(mode)
        case (359); call tp359(mode)
        case (360); call tp360(mode)
        case (361); call tp361(mode)
        case (362); call tp362(mode)
        case (364); call tp364(mode)
        case (365); call tp365(mode)
        case (366); call tp366(mode)
        case (367); call tp367(mode)
        case (368); call tp368(mode)
        case (369); call tp369(mode)
        case (370); call tp370(mode)
        case (371); call tp371(mode)
        case (372); call tp372(mode)
        case (373); call tp373(mode)
        case (374); call tp374(mode)
        case (375); call tp375(mode)
        case (376); call tp376(mode)
        case (377); call tp377(mode)
        case (378); call tp378(mode)
        case (379); call tp379(mode)
        case (380); call tp380(mode)
        case (381); call tp381(mode)
        case (382); call tp382(mode)
        case (383); call tp383(mode)
        case (384); call tp384(mode)
        case (385); call tp385(mode)
        case (386); call tp386(mode)
        case (387); call tp387(mode)
        case (388); call tp388(mode)
        case (389); call tp389(mode)
        case (391); call tp391(mode)
        case (392); call tp392(mode)
        case (393); call tp393(mode)
        case (394); call tp394(mode)
        case (395); call tp395(mode)
    case default
        error stop 'hs_problems_module: no such problem'
    end select

    end subroutine call_problem
!*******************************************************************************

!*******************************************************************************
!>
!  the definition of problem `id`: size, starting point, bounds, and known
!  solution. This must be called before evaluating a problem (and again
!  when switching problems: the original code keeps constant derivative
!  elements, set here, in its COMMON blocks).

    subroutine hs_setup(id, prob)

    integer,          intent(in)  :: id
    type(hs_problem), intent(out) :: prob

    integer :: i

    if (hs_index(id) == 0) error stop 'hs_setup: no such problem'
    lxl = .false.; lxu = .false.; lex = .false.
    xl = 0.0_dp; xu = 0.0_dp; fex = 0.0_dp; xex = 0.0_dp
    ! (many problems set the constant elements of their derivatives here, in
    ! mode 1, and never again, so these must be cleared now -- and only now:)
    gf_ = 0.0_dp; gg_ = 0.0_dp
    call call_problem(id, 1)

    prob%id = id
    prob%n  = n_
    prob%me = neli + nenl
    prob%m  = nili + ninl + prob%me
    prob%x0 = x_(1:n_)
    allocate(prob%x_lb(n_), prob%x_ub(n_))
    do i = 1, n_
        prob%x_lb(i) = merge(xl(i), -hs_infinity, lxl(i))
        prob%x_ub(i) = merge(xu(i),  hs_infinity, lxu(i))
    end do
    ! (a few problems -- TP358, 369, 376, 379, 383 -- clip x to XL/XU inside
    ! their function evaluations, also on a side declared unbounded, where
    ! XL/XU were never set: make that side really unbounded, or e.g. TP379's
    ! objective would be constant, with every x clipped to 0)
    where (.not. lxl(1:n_)) xl(1:n_) = -hs_infinity
    where (.not. lxu(1:n_)) xu(1:n_) =  hs_infinity
    allocate(prob%c_lb(prob%m), prob%c_ub(prob%m))
    prob%c_lb = 0.0_dp
    prob%c_ub = hs_infinity
    prob%c_ub(prob%m-prob%me+1:prob%m) = 0.0_dp
    prob%exact  = lex
    prob%f_star = fex
    prob%x_star = xex(1:n_)

    end subroutine hs_setup
!*******************************************************************************

!*******************************************************************************
!>
!  the objective of problem `id` at `x` (after [[hs_setup]] for that problem,
!  as for all the evaluation routines).

    subroutine hs_f(id, x, f)

    integer,                intent(in)  :: id
    real(dp), dimension(:), intent(in)  :: x
    real(dp),               intent(out) :: f

    x_(1:size(x)) = x
    call call_problem(id, 2)
    f = fx_

    end subroutine hs_f
!*******************************************************************************

!*******************************************************************************
!>
!  the objective gradient of problem `id` at `x`. (Some problems' original
!  code provides no gradients, or incorrect ones -- check them before use.)

    subroutine hs_g(id, x, g)

    integer,                intent(in)  :: id
    real(dp), dimension(:), intent(in)  :: x
    real(dp), dimension(:), intent(out) :: g

    x_(1:size(x)) = x
    call call_problem(id, 2)   ! (some problems compute shared terms in mode 2)
    call call_problem(id, 3)
    g = gf_(1:size(x))

    end subroutine hs_g
!*******************************************************************************

!*******************************************************************************
!>
!  the constraints of problem `id` at `x`: the inequalities first, then the
!  equalities (see [[hs_problem]]).

    subroutine hs_c(id, x, c)

    integer,                intent(in)  :: id
    real(dp), dimension(:), intent(in)  :: x
    real(dp), dimension(:), intent(out) :: c

    if (size(c) == 0) return
    x_(1:size(x)) = x
    index1 = .true.
    call call_problem(id, 4)
    c = g_(1:size(c))

    end subroutine hs_c
!*******************************************************************************

!*******************************************************************************
!>
!  the dense constraint Jacobian of problem `id` at `x` (`jac(i,j)` is the
!  derivative of constraint `i` with respect to `x(j)`). (As for [[hs_g]],
!  check before use.)

    subroutine hs_jac(id, x, jac)

    integer,                  intent(in)  :: id
    real(dp), dimension(:),   intent(in)  :: x
    real(dp), dimension(:,:), intent(out) :: jac

    if (size(jac,1) == 0) return
    x_(1:size(x)) = x
    index1 = .true.
    index2 = .true.
    call call_problem(id, 4)   ! (some problems compute shared terms in mode 4)
    call call_problem(id, 5)
    jac = gg_(1:size(jac,1), 1:size(jac,2))

    end subroutine hs_jac
!*******************************************************************************

    end module hs_problems_module
!*******************************************************************************
