name = "sqpopt"
version = "0.1.0"
license = "MIT"
author = "Jacob Williams"
description = "Modern Fortran SQP OPTimizer"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[fortran]
source-form = "default"

[dependencies]

[dev-dependencies]
slsqp = { git="https://github.com/jacobwilliams/slsqp.git" }
